service: mismo-precio-web

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-west-2
  memorySize: 264
  timeout: 15
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    
  deploymentBucket:
    name: mismo-precio-web
    versioning: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-plugin-warmup
  - serverless-deployment-bucket

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    certificateName: '*.mismoprecio.com'
    certificateArn: arn:aws:acm:us-west-2:107982701859:certificate/e306f18d-4250-4e02-a0fc-3a9d400d0f99
    hostedZoneId: Z01974403AN6AOYAUWJ1D
    basePath: ''
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true
    endpointType: regional

functions:
  next:
    handler: index.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}
    warmup: true